# Generated by Django 4.0.6 on 2022-09-21 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('middle_name', models.CharField(max_length=255)),
                ('birthdate', models.DateField()),
                ('photo', models.ImageField(upload_to='')),
                ('phone_number', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Навык')),
                ('level', models.CharField(choices=[('E', 'Beginner'), ('D', 'Moderate'), ('C', 'Good'), ('B', 'Very good'), ('A', 'Excellent')], default='E', max_length=1)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Язык')),
                ('level', models.CharField(choices=[('A0', 'Beginner'), ('A1', 'Elementary'), ('A2', 'Pre Intermediate'), ('B1', 'Intermediate'), ('B2', 'Upper intermediate'), ('C1', 'Advanced'), ('C2', 'Proficient')], default='A0', max_length=2)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=255, verbose_name='Должность')),
                ('company', models.CharField(max_length=255, verbose_name='Работодатель')),
                ('starting_date', models.DateField()),
                ('ending_date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.CharField(max_length=255, verbose_name='Образование')),
                ('institution', models.CharField(max_length=255, verbose_name='Учебное заведение')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('starting_date', models.DateField()),
                ('ending_date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
        ),
    ]
