# Generated by Django 4.0.6 on 2022-09-23 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='ending_date',
            field=models.DateField(verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='education',
            name='starting_date',
            field=models.DateField(verbose_name='Дата начало'),
        ),
    ]
