# Generated by Django 4.0.6 on 2022-07-21 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=40)),
                ('telegram_account', models.CharField(blank=True, max_length=255, null=True)),
                ('skype_account', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
